"use client";

import { FormEvent, useEffect, useState } from "react";
import { Fingerprint, Plus, X } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { buttonClass, ErrorMessage, inputClass, PageState, Panel } from "@/components/ui";
import { api, money } from "@/lib/api";

type Employee = { id: number; name: string; nic: string; phone: string; position: string; base_salary: string; fingerprint_id: string; active: boolean };
export default function EmployeesPage() {
  const [employees, setEmployees] = useState<Employee[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  function load() { api<{ data: Employee[] }>("/employees?active_only=1").then((result) => setEmployees(result.data)).catch((caught) => setError(caught.message)); }
  useEffect(() => { load(); }, []);
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; try { await api("/employees", { method: "POST", body: JSON.stringify(Object.fromEntries(new FormData(form))) }); form.reset(); setOpen(false); load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not add employee."); } }
  return <AppShell title="Workshop team" eyebrow={`${employees.length} active employees`} action={<button onClick={() => setOpen(true)} className="flex h-10 items-center gap-2 bg-[#f5c842] px-3 text-sm font-semibold"><Plus size={18} /><span className="hidden sm:inline">Add employee</span></button>}>{error && <div className="mb-5"><ErrorMessage message={error} /></div>}{employees.length === 0 && !error ? <PageState message="No employees have been added." /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{employees.map((employee) => <Panel key={employee.id} className="p-5"><div className="flex items-start justify-between"><span className="grid size-12 place-items-center bg-[#242723] font-display text-xl text-white">{employee.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</span><span className="flex items-center gap-1 bg-[#167c73]/10 px-2 py-1 text-[10px] font-bold text-[#167c73]"><Fingerprint size={13} />{employee.fingerprint_id}</span></div><h2 className="mt-5 font-display text-2xl font-semibold uppercase">{employee.name}</h2><p className="text-sm text-[#167c73]">{employee.position}</p><div className="mt-5 grid grid-cols-2 gap-3 border-t border-[#d7d3c8] pt-4 text-xs"><div><p className="text-[#6f746e]">NIC</p><strong>{employee.nic}</strong></div><div><p className="text-[#6f746e]">Phone</p><strong>{employee.phone}</strong></div><div className="col-span-2"><p className="text-[#6f746e]">Base salary</p><strong>{money(employee.base_salary)}</strong></div></div></Panel>)}</div>}{open && <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/55 p-4"><form onSubmit={add} className="my-8 w-full max-w-xl bg-[#f3f0e8]"><div className="flex items-center justify-between border-b border-[#d7d3c8] p-5"><h2 className="font-display text-3xl font-semibold uppercase">Add employee</h2><button type="button" onClick={() => setOpen(false)}><X /></button></div><div className="grid gap-4 p-5 sm:grid-cols-2">{[["name", "Full name"], ["nic", "NIC"], ["phone", "Phone"], ["position", "Position"], ["base_salary", "Base salary"], ["overtime_hourly_rate", "OT hourly rate"], ["fingerprint_id", "Fingerprint ID"]].map(([name, label]) => <label key={name} className={`text-xs font-bold uppercase ${name === "fingerprint_id" ? "sm:col-span-2" : ""}`}>{label}<input name={name} required type={name.includes("salary") || name.includes("rate") ? "number" : "text"} step="0.01" className={`${inputClass} mt-2`} /></label>)}</div><div className="flex justify-end border-t border-[#d7d3c8] p-5"><button className={buttonClass}>Save employee</button></div></form></div>}</AppShell>;
}